spring.application.name=demo

server.port=8080

#Change your application context path(/ for root)
server.servlet.context-path=/

#Add the property to allow custom beans to override default framework beans.
spring.main.allow-bean-definition-overriding=true